[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
lto = true
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[build]
rustflags = ["-C", "link-arg=-Teikos.ld"]
target = "i686-eikos-teleia.json"
