---
name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  changes:
    name: Check changed files
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.rs
            **/*.asm
            eikos.ld
            Cargo.toml
            Cargo.lock

  build:
    name: Build Kernel
    needs: changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nasm
        run: sudo apt-get update && sudo apt-get install -y nasm
      - name: Build
        run: cargo build --verbose
